### ISSUE TITLE
Runtime Error at `select_bootstrap_date'

### ISSUE THREAD

**Issue by gmmundy** [akarzim/capybara-bootstrap-datepicker#10]
I'm getting a RuntimeError from this gem. Not sure why.

```
 Failure/Error: select_date(2.weeks.ago, from: "Last repair date", format: "%Y-%m-%d")
     RuntimeError:
     # /Users/Dustin/.rvm/gems/ruby-2.2.3/bundler/gems/capybara-bootstrap-datepicker-125a4769edf5/lib/capybara-bootstrap-datepicker.rb:53:in `select_bootstrap_date'
     # /Users/Dustin/.rvm/gems/ruby-2.2.3/bundler/gems/capybara-bootstrap-datepicker-125a4769edf5/lib/capybara-bootstrap-datepicker.rb:22:in `select_date'
     # ./spec/features/repair_shop_adds_new_vehicle_spec.rb:32:in `block (2 levels) in <top (required)>'
```

**Comment by szromek** [comment]
The same here:
```
Failure/Error: select_date(5.years.ago, from: 'Start date')
     RuntimeError:
     # /Users/krzysztof/gems/riseto/ruby/2.3.0/gems/capybara-bootstrap-datepicker-0.1.1/lib/capybara-bootstrap-datepicker.rb:40:in `select_bootstrap_date'
     # /Users/krzysztof/gems/riseto/ruby/2.3.0/gems/capybara-bootstrap-datepicker-0.1.1/lib/capybara-bootstrap-datepicker.rb:14:in `select_date'
     # ./spec/features/members/qualifications/edit_spec.rb:166:in `block (3 levels) in <top (required)>'
```
